### ISSUE TITLE
Well done brother but im facing compilation issue i have sett kernel path and also all other things done

### ISSUE THREAD

**Issue by gmbest89** [ValdikSS/huawei_oled_hijack#1]
but it producing lots off errors

**Comment by ValdikSS** [comment]
You absolutely don't need kernel to compile this library. What exact errors do you have?

**Comment by gmbest89** [comment]
I m talking about this one unlockmtd.c source

**Comment by ValdikSS** [comment]
How's that connected with this library? Do not use projects' issues for unrelated questions.
